### ISSUE TITLE
set-color! not working

### ISSUE THREAD

**Issue by DexterLagan** [massung/r-cade#13]
No matter which parameters I pass to (set-color!), the color is always set to black. Racket 7.5, 7.6, Windows 10, CSFML 2.5, libsndfile-1.0.28.

  Steps to reproduce:
(set-color! 7 255 255 255)
(color 7)
(draw ...)
-> nothing drawn on black background.

**Comment by massung** [comment]
I already discovered the problem and it's fixed in a branch. Thanks for finding this.

**Comment by massung** [comment]
Fixed as of commit fa4afaa8cd80f7515a2a39b07511ea5bb7d63d6a.
