### ISSUE TITLE
Dependencies documentation 

### ISSUE THREAD

**Issue by oneEdoubleD** [massung/r-cade#2]
Cool idea! I had an issue finding decent documentation on correctly installing the CSFML files as did someone else on HackerNews, so if this is aimed at kids (who may well be better at these things than me nowadays!) would you be able to expand on your documentation perhaps linking to good sources for all three platforms? I’ve not gotten around to the OpenAL bit, so maybe that’s required too. 

If I find something first, when I take another look later, I’ll submit a PR.

**Comment by massung** [comment]
Documentation is definitely something that's still a work-in-progress. I'm thinking a DEPENDENCIES file describing each platform may be in order (with a link to it in the README). But I don't know exactly what to do for MacOS X and Linux, so I'd need a little assistance on that front.

**Comment by massung** [comment]
I've taken a quick stab at a DEPENDENCIES.md file (and the README now links to it).

For Linux it will need some love by someone who knows Linux for the CSFML dynamic libraries, and if someone uses RH or CentOS, if there are yum installers for OpenAL and/or libsndfile1, that's be great to have added as well.

**Comment by massung** [comment]
Created a website for r-cade, which has an entire page dedicated to setup instructions per platform. Closing.
