### ISSUE TITLE
Ubuntu 19.10 - ffi-lib: couldn't open "libcsfml-audio.so"

### ISSUE THREAD

**Issue by DexterLagan** [massung/r-cade#21]
I'm trying to run the most basic program for R-Cade, on Ubuntu 19.10. 
CSFML and other required libs are correctly installed. I'm getting the typical missing library error. I'm guessing it should be looking for 'libcsfml-audio.so.2.5', instead of libcsfml-audio.so.

../../../../../usr/share/racket/collects/ffi/unsafe.rkt:131:0: ffi-lib: couldn't open "libcsfml-audio.so" (libcsfml-audio.so: cannot open shared object file: No such file or directory)

$ locate -i libcsfml
/usr/lib/x86_64-linux-gnu/libcsfml-audio.so.2.5
/usr/lib/x86_64-linux-gnu/libcsfml-audio.so.2.5.0
/usr/share/doc/libcsfml-audio2.5
/usr/share/doc/libcsfml-audio2.5/changelog.Debian.gz
/usr/share/doc/libcsfml-audio2.5/copyright
/var/lib/dpkg/info/libcsfml-audio2.5:amd64.list
/var/lib/dpkg/info/libcsfml-audio2.5:amd64.md5sums
/var/lib/dpkg/info/libcsfml-audio2.5:amd64.shlibs
/var/lib/dpkg/info/libcsfml-audio2.5:amd64.symbols
/var/lib/dpkg/info/libcsfml-audio2.5:amd64.triggers

$ uname -a
Linux x220 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I also tried installing CSFML dev, with:
  sudo apt-get install libsfml-dev
...but it didn't help.

Cheers!

Dexter

**Comment by DexterLagan** [comment]
I got the audio lib to work after all, by running

sudo ln /usr/lib/x86_64-linux-gnu/libcsfml-audio.so.2.5 /usr/lib/x86_64-linux-gnu/libcsfml-audio.so

However the graphics part isn't working so well: I got rid of the ffi error message by running

sudo ln /usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.5 /usr/lib/x86_64-linux-gnu/libcsfml-graphics.so

I'm now getting this error upong trying to run the basic demo:

../../../../../usr/share/racket/collects/racket/private/more-scheme.rkt:261:28: ffi-obj: couldn't get "sfCircleShape_destroy" from "libcsfml-graphics.so" (/usr/lib/x86_64-linux-gnu/libcsfml-graphics.so: undefined symbol: sfCircleShape_destroy)

Finally, I tried making a symlink to the graphics 2.5.1:

sudo ln /usr/lib/x86_64-linux-gnu/libsfml-graphics.so.2.5.1 /usr/lib/x86_64-linux-gnu/libcsfml-graphics.so

But I'm getting the same error.

**Comment by elephanter** [comment]
Hello, I have same troubles with csfml. 
This helps me rebuild csfml from sources https://pryp.in/blog/12/build-sfml-and-csfml-on-linux.html
and everything works fine

**Comment by DexterLagan** [comment]
Great!! Thanks a bunch.

 

Dex

**Comment by massung** [comment]
Thanks for the link! I'll add it to the setup page of the site.
