### ISSUE TITLE
Windows 10 - 'quotient: contract violation' upon running shortest game

### ISSUE THREAD

**Issue by DexterLagan** [massung/r-cade#22]
I'm getting an error running the shortest game:

. . ..\..\Program Files\Racket-7.6.0.18\collects\racket\private\kw.rkt:1393:47: quotient: contract violation
  expected: integer?
  given: 614.4
  argument position: 1st
  other arguments...:

  I tried with 7.6 and the latest snapshot (7.6.0.18), same error. Same lib version as my other bug reports, different computer. Strangely, bigger games such as Horse Derby run well!

Cheers,

Dexter

**Comment by massung** [comment]
Sorry, but I need a bit more than "shortest game". Is it one of the tutorials on the website or an example from the repo? If it's something you've copy/pasted and/or modified, is it short enough to just paste the code here?

**Comment by DexterLagan** [comment]
Yes it is one of the examples, I believe the first example in the tutorial (which displays the rolling frame count).

Dex

**Comment by massung** [comment]
Not sure what to say. All the tutorial code from the homepage works perfect for me as do all the example games (I'm also on Windows 10).

Are you sure you didn't edit the code in any way?

**Comment by DexterLagan** [comment]
No I copy-pasted the code, it works on all my other computers. I’ll let you know if I get to the bottom of it. 

Dex

**Comment by massung** [comment]
I found a bit of code that might be causing it. I'll change it up a bit and see if that helps.

**Comment by massung** [comment]
Ok, I believe 2b3f216401f48f45a1a9fa949efd2ab46fea384e fixes this. I've told raco to rescan the project. Version 0.3.2 should be available shortly. Please let me know if this takes care of it.

**Comment by DexterLagan** [comment]
Thanks I’ll let you know!

Dex

**Comment by massung** [comment]
I'm going to assume this is fixed. Just re-open if you hit this again.

**Comment by DexterLagan** [comment]
Apologies I wasn’t able to reproduce the problem on my other systems. The one that had the problem isn’t available at the moment. I’ll do my best to get it running and see if it’s fixed. Cheers!

Dex
