### ISSUE TITLE
How to distribute standalone Windows executables?

### ISSUE THREAD

**Issue by Softwave** [massung/r-cade#27]
Firstly, this library is so fun and wonderful! I have made some small games with it already, but I have a problem I haven't seen dealt with anywhere in the documentation. 

I try putting all of the csfml dlls and the libsndfile dll into the same directory as the DrRacket produced executable and even then nothing happens when I run the produced program. Not on any of the Dr.Racket settings I could find. What do I need to include in the games directory?

**Comment by massung** [comment]
So, I've not come across a way for Racket - when building the EXE - to bundle non-Racket DLLs in the final app. Best I've done is just build the EXE as-is and distribute the DLLs myself with the EXE along-side it.
