### ISSUE TITLE
Can't launch snake game

### ISSUE THREAD

**Issue by Marcelli** [massung/r-cade#28]
Hello, 

I have install r-cade and wanted to test the example games. I tried to launch snake, but without success, I get:

`
.../ffi/unsafe.rkt:131:0: ffi-lib: could not load foreign library
  path: libcsfml-audio.so
  system error: libcsfml-audio.so: cannot open shared object file: No such file or directory
Interactions disabled: racket does not support a REPL (no #%top-interaction)
`

I have installed r-cade with the needed libraries, using the instructions here https://r-cade.io/setup and here https://pryp.in/blog/12/build-sfml-and-csfml-on-linux.html to install on ubuntu.

Thank you for your help, in advance!

**Comment by Marcelli** [comment]
The problem was addressed in another in a now closed issue (still not working for me, though).

**Comment by massung** [comment]
Is the library in your PATH?

I don't have a Linux machine, so I been dependent on others for their assistance on that front. But, I'm happy to help however I can.

**Comment by Marcelli** [comment]
CSFML seems installed just fine:
`
ldconfig -v | grep libcsfml
	libcsfml-graphics.so.2.5 -> libcsfml-graphics.so.2.5.0
	libcsfml-network.so.2.5 -> libcsfml-network.so.2.5.0
	libcsfml-audio.so.2.5 -> libcsfml-audio.so.2.5.0
	libcsfml-window.so.2.5 -> libcsfml-window.so.2.5.0
	libcsfml-system.so.2.5 -> libcsfml-system.so.2.5.0
`
I have installed the CSFML bindings via the package manager.
But I get the error if I (require csfml) in Racket.

**Comment by Marcelli** [comment]
OK, I have found the issue: Needed only to enter 
`sudo ldconfig `
to reload the libraries.
Thanks!
