### ISSUE TITLE
Repository lacks documentation

### ISSUE THREAD

**Issue by dented42** [massung/r-cade#3]
The documentation does live in the repository, which makes offline development difficult. Also having scribble documentation be part of the package allows raco to link it into the main racket documentation which, among other things, makes it searchable alongside the rest of the racket docs.

**Comment by massung** [comment]
This is something I definitely want to do, but I haven't found any trivial examples of scribble documentation to learn from (admittedly it's been a low priority thus far). 

Most of the scribble docs I see are just about generating generic markup. I'm hoping there's just a subset of it that's used for Racket documentation.

If you have a link for me with an example package + functions documented, I'd be happy to.

**Comment by massung** [comment]
I've added scribble documentation that should be available when the Racket package system next builds (in the next 24 hours).
