### ISSUE TITLE
Running more than one R-cade program at the same time crashes DrRacket

### ISSUE THREAD

**Issue by GrazHero** [massung/r-cade#8]
If I run a program from DrRacket, and then click run again to start another instance, the first instance of the program becomes completely unresponsive. DrRacket and the second instance of the program both continue to work fine though. If I click run again, the second instance becomes unresponsive, and so on. If I forcibly close one of the unresponsive windows, DrRacket crashes entirely.

I can only confirm that this happens on Linux.

**Comment by massung** [comment]
So, I can definitely confirm the behavior as it's happened to me plenty during development (on Windows). 

It doesn't "crash" DrRacket. By force closing the window you're telling the OS to terminate the parent process, which is DrRacket. If you close DrRacket instead (nicely), all the game windows terminate properly without any crashes.

That said, it definitely _is_ annoying and I'm looking for ways to fix it.

**Comment by GrazHero** [comment]
> It doesn't "crash" DrRacket.

Right, my bad. I couldn't think of a concise way to accurately describe what it was doing, for the summary of the issue.

**Comment by massung** [comment]
I have a fix for this. It should go through with the next raco update (likely in a few hours, 24 hours from now at the latest).

I'll close once the package update happens and someone else can confirm it's good for them. It should handle re-run, debug, and stop buttons from DrRacket.
