### ISSUE TITLE
Certain short music loops can become incredibly distorted 

### ISSUE THREAD

**Issue by GrazHero** [massung/r-cade#9]
For some reason, certain short music loops can sometimes become very distorted after a couple iterations. There appears to be an element of nondeterminism to it too. Sorry, I have a feeling this one's gonna be tough to track down.

Video showing the problem in action (major volume warning): https://www.youtube.com/watch?v=SqTo2fBQQO4

**Comment by massung** [comment]
Fixed as of fa4afaa8cd80f7515a2a39b07511ea5bb7d63d6a.
